/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppErrorDevSection: typeof import('./src/components/AppError/AppErrorDevSection.vue')['default']
    AppErrorPage: typeof import('./src/components/AppError/AppErrorPage.vue')['default']
    AuthLayout: typeof import('./src/components/Layout/main/AuthLayout.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    DataTable: typeof import('./src/components/ui/data-table/DataTable.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
    SidebarLinks: typeof import('./src/components/Layout/SidebarLinks.vue')['default']
    TopNavbar: typeof import('./src/components/Layout/TopNavbar.vue')['default']
  }
}
